# Generated by Django 5.2.8 on 2025-11-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArquivoModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_original", models.CharField(max_length=255)),
                (
                    "nome_sugerido",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("nome_final", models.CharField(blank=True, max_length=255, null=True)),
                ("tipo_arquivo", models.CharField(max_length=50)),
                ("tamanho", models.BigIntegerField()),
                ("data_upload", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="pendente", max_length=20)),
            ],
            options={
                "db_table": "arquivo",
                "ordering": ["-id"],
            },
        ),
    ]
